import { CloudFrontClient, CreatePublicKeyCommand, CreateKeyGroupCommand } from "@aws-sdk/client-cloudfront";
import { SecretsManagerClient, CreateSecretCommand, PutSecretValueCommand } from "@aws-sdk/client-secrets-manager";
import { CloudFormationCustomResourceEvent, CloudFormationCustomResourceEventCommon, CloudFormationCustomResourceHandler } from "aws-lambda";
import crypto from "crypto";
import { AppConfig } from "../model/app-config";

// Initialize v3 clients
const cloudFrontClient = new CloudFrontClient({ region: process.env.AWS_REGION });
const secretsClient = new SecretsManagerClient({ region: process.env.AWS_REGION });

/**
 * Generate RSA key pair (2048 bits)
 */
function generateKeyPair() {
  return crypto.generateKeyPairSync("rsa", {
    modulusLength: 2048,
    publicKeyEncoding: { type: "spki", format: "pem" },
    privateKeyEncoding: { type: "pkcs8", format: "pem" },
  });
}

/**
 * Create a CloudFront Public Key
 */
async function createCloudFrontPublicKey(publicKey: string, publicKeyName: string) {
  const cmd = new CreatePublicKeyCommand({
    PublicKeyConfig: {
      CallerReference: Date.now().toString(),
      Name: publicKeyName,
      EncodedKey: publicKey,
      Comment: "Auto-generated by CDK Custom Resource",
    },
  });

  const resp = await cloudFrontClient.send(cmd);
  return resp.PublicKey?.Id;
}

/**
 * Create a Key Group for the Public Key
 */
async function createKeyGroup(publicKeyId: string) {
  const cmd = new CreateKeyGroupCommand({
    KeyGroupConfig: {
      Name: `CFKeyGroup-${Date.now()}`,
      Items: [publicKeyId],
      Comment: "Auto-generated by CDK Custom Resource",
    },
  });

  const resp = await cloudFrontClient.send(cmd);
  return resp.KeyGroup?.Id;
}

/**
 * Store the private key in Secrets Manager (create or update)
 */
async function storePrivateKey(secretName: string, privateKey: string) {
  try {
    await secretsClient.send(
      new CreateSecretCommand({
        Name: secretName,
        SecretString: JSON.stringify({ privateKey }),
      })
    );
  } catch (err: any) {
    if (err.name === "ResourceExistsException") {
      await secretsClient.send(
        new PutSecretValueCommand({
          SecretId: secretName,
          SecretString: JSON.stringify({ privateKey }),
        })
      );
    } else {
      throw err;
    }
  }
}

export const handler = async (event:CloudFormationCustomResourceEvent) => {
  console.log("Event:", JSON.stringify(event));
  let physicalId = "CloudFrontKeyPairResource";
  

  if (event.RequestType === "Delete") {
    physicalId = event.PhysicalResourceId;
    return {
      PhysicalResourceId: physicalId,
    };
  }

  if (event.RequestType === "Create" || event.RequestType === "Update") {
    //Generate Key Pair
    const { publicKey, privateKey } = generateKeyPair();

    //Create CloudFront Public Key
    const publicKeyName = AppConfig.getEnvVar("CLOUDFRONT_SIGNING_KEY");
    const publicKeyId = await createCloudFrontPublicKey(publicKey, publicKeyName);
    if (!publicKeyId) throw new Error("Failed to create CloudFront public key");

    //Create Key Group
    const keyGroupId = await createKeyGroup(publicKeyId);
    if (!keyGroupId) throw new Error("Failed to create Key Group");

    //Store private key in Secrets Manager
    const secretName = AppConfig.getEnvVar("CLOUDFRONT_SIGNING_SECRET");
    await storePrivateKey(secretName, privateKey);

    return {
      PhysicalResourceId: publicKeyId,
      Data: {
        KeyPairId: publicKeyId,
        KeyGroupId: keyGroupId,
        SecretName: secretName,
      },
    };
  }

  // Should not reach here
  return { PhysicalResourceId: physicalId };
};
